//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
namespace Forest.Data
{

    
    public class ForestEntities : DbContext
{
    public ForestEntities() : base("name=ForestEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Music_Category> Music_Category { get; set; }
    public virtual DbSet<Music_Recording> Music_Recording { get; set; }
    }

}